In [1]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
ratings = pd.DataFrame({
    "user": ["A","A","B","B","C","C"],
    "event": ["AI","Football","AI","Music","Football","Music"],
    "rating": [5,3,4,2,5,4]
})

ratings

  user     event  rating
0    A        AI       5
1    A  Football       3
2    B        AI       4
3    B     Music       2
4    C  Football       5
5    C     Music       4

In [3]:
matrix = ratings.pivot_table(
    index="user",
    columns="event",
    values="rating"
).fillna(0)

matrix

event   AI  Football  Music
user
A      5.0       3.0    0.0
B      4.0       0.0    2.0
C      0.0       5.0    4.0

In [4]:
user_similarity = cosine_similarity(matrix)

user_similarity

array([[1.        , 0.76696499, 0.40175369],
       [0.76696499, 1.        , 0.27937212],
       [0.40175369, 0.27937212, 1.        ]])

In [5]:
similarity_df = pd.DataFrame(
    user_similarity,
    index=matrix.index,
    columns=matrix.index
)

similarity_df

user         A         B         C
user
A     1.000000  0.766965  0.401754
B     0.766965  1.000000  0.279372
C     0.401754  0.279372  1.000000

In [6]:
similar_users = similarity_df["A"].sort_values(ascending=False)

similar_users

user
A    1.000000
B    0.766965
C    0.401754
Name: A, dtype: float64

In [7]:
most_similar_user = similar_users.index[1]

most_similar_user

'B'

In [8]:
matrix.loc[most_similar_user]

event
AI          4.0
Football    0.0
Music       2.0
Name: B, dtype: float64

In [9]:
recommendation = matrix.loc[most_similar_user]

recommendation

event
AI          4.0
Football    0.0
Music       2.0
Name: B, dtype: float64